"""empty message

Revision ID: 14f4eca16e35
Revises: 453a9b3bfe4d
Create Date: 2019-02-17 21:48:18.412608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f4eca16e35'
down_revision = '453a9b3bfe4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_fields', sa.Column('fieldCategory', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata_fields', 'fieldCategory')
    # ### end Alembic commands ###
