"""empty message

Revision ID: 157c0e3ba75e
Revises: 36003ebd3bcc
Create Date: 2019-04-09 11:54:27.126528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157c0e3ba75e'
down_revision = '36003ebd3bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fieldUniqueName', table_name='metadata_fields')
    op.drop_index('rsFieldID', table_name='metadata_fields')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('rsFieldID', 'metadata_fields', ['rsFieldID'], unique=True)
    op.create_index('fieldUniqueName', 'metadata_fields', ['fieldUniqueName'], unique=True)
    # ### end Alembic commands ###
