"""empty message

Revision ID: 34e7992ce06b
Revises: 4035292a735a
Create Date: 2019-10-08 13:12:51.539926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34e7992ce06b'
down_revision = '4035292a735a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tapes', 'spaceAvailable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tapes', sa.Column('spaceAvailable', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
