"""empty message

Revision ID: 4035292a735a
Revises: 6c066d722cf6
Create Date: 2019-10-08 11:35:23.590895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4035292a735a'
down_revision = '6c066d722cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tapes', sa.Column('mountpoint', sa.String(length=100), nullable=True))
    op.add_column('tapes', sa.Column('spaceAvailable', sa.Integer(), nullable=True))
    op.drop_column('tapes', 'aOrB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tapes', sa.Column('aOrB', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('tapes', 'spaceAvailable')
    op.drop_column('tapes', 'mountpoint')
    # ### end Alembic commands ###
