"""empty message

Revision ID: 453a9b3bfe4d
Revises: e71364e97d3d
Create Date: 2019-02-14 12:47:34.494816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453a9b3bfe4d'
down_revision = 'e71364e97d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('primaryAssetID', sa.String(length=60), nullable=True))
    op.add_column('data_sources', sa.Column('secondaryAssetID', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'secondaryAssetID')
    op.drop_column('data_sources', 'primaryAssetID')
    # ### end Alembic commands ###
