"""empty message

Revision ID: 6c066d722cf6
Revises: 88a663188396
Create Date: 2019-10-03 18:05:07.487231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c066d722cf6'
down_revision = '88a663188396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tape_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_version', sa.String(length=50), nullable=True),
    sa.Column('b_version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aOrB', sa.String(length=10), nullable=True),
    sa.Column('tapeBarcode', sa.String(length=10), nullable=True),
    sa.Column('tapeUUID', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('formattedDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tapes')
    op.drop_table('tape_ids')
    # ### end Alembic commands ###
