"""empty message

Revision ID: 88a663188396
Revises: ed9edef32cb3
Create Date: 2019-04-11 17:10:53.476712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a663188396'
down_revision = 'ed9edef32cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('tertiaryAssetID', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'tertiaryAssetID')
    # ### end Alembic commands ###
