"""empty message

Revision ID: 9c5c0997178e
Revises: 34e7992ce06b
Create Date: 2019-10-08 13:13:17.978612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5c0997178e'
down_revision = '34e7992ce06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tapes', sa.Column('spaceAvailable', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tapes', 'spaceAvailable')
    # ### end Alembic commands ###
