"""empty message

Revision ID: 9e8078d90e76
Revises: b1ddfc575736
Create Date: 2018-12-28 13:09:21.124328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e8078d90e76'
down_revision = 'b1ddfc575736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('deptname', sa.String(length=60), nullable=True))
    op.drop_index('name', table_name='departments')
    op.create_unique_constraint(None, 'departments', ['deptname'])
    op.drop_column('departments', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('name', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'departments', type_='unique')
    op.create_index('name', 'departments', ['name'], unique=True)
    op.drop_column('departments', 'deptname')
    # ### end Alembic commands ###
