"""empty message

Revision ID: c3900342ae24
Revises: 803239820882
Create Date: 2019-01-10 21:57:16.896972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3900342ae24'
down_revision = '803239820882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fieldName', sa.String(length=100), nullable=True),
    sa.Column('fieldUniqueName', sa.String(length=60), nullable=True),
    sa.Column('dataSource', sa.String(length=60), nullable=True),
    sa.Column('rsFieldID', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fieldUniqueName'),
    sa.UniqueConstraint('rsFieldID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_fields')
    # ### end Alembic commands ###
