"""empty message

Revision ID: e71364e97d3d
Revises: eddd14d43289
Create Date: 2019-02-12 21:57:25.299680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e71364e97d3d'
down_revision = 'eddd14d43289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_fields', sa.Column('dataSource_id', sa.Integer(), nullable=True))
    op.add_column('metadata_fields', sa.Column('fieldSourceName', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'metadata_fields', 'data_sources', ['dataSource_id'], ['id'])
    op.drop_column('metadata_fields', 'dataSource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_fields', sa.Column('dataSource', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'metadata_fields', type_='foreignkey')
    op.drop_column('metadata_fields', 'fieldSourceName')
    op.drop_column('metadata_fields', 'dataSource_id')
    # ### end Alembic commands ###
