"""empty message

Revision ID: ed9edef32cb3
Revises: 157c0e3ba75e
Create Date: 2019-04-09 12:42:51.778363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9edef32cb3'
down_revision = '157c0e3ba75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'metadata_fields', ['fieldUniqueName'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'metadata_fields', type_='unique')
    # ### end Alembic commands ###
