"""empty message

Revision ID: eddd14d43289
Revises: c3900342ae24
Create Date: 2019-02-12 15:45:38.249565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddd14d43289'
down_revision = 'c3900342ae24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('IPaddress', table_name='data_sources')
    op.drop_index('username', table_name='data_sources')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'data_sources', ['username'], unique=True)
    op.create_index('IPaddress', 'data_sources', ['IPaddress'], unique=True)
    # ### end Alembic commands ###
